name: R2C
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - openjdk=23.0.2
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.13=hb9d3cd8_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - bbmap=39.19=he5f24ec_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - boost-cpp=1.85.0=h3c6214e_4
  - brotli-python=1.1.0=py313h46c70d0_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - expat=2.6.4=h5888daf_0
  - fastqc=0.12.1=hdfd78af_0
  - ffq=0.3.1=pyhdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h48d6fc4_0
  - frozendict=2.4.6=py313h536fd9c_0
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.4.0=h76408a6_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.21=h566b1c6_1
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.12.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - kaleido-core=0.2.1=h3644ca4_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.12.1=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgff=2.0.0=h077b44d_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.82.2=h2ff4ddf_1
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjemalloc=5.3.0=h5888daf_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hc4654cb_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.6=h8d12d68_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lxml=5.3.1=py313h6eb7059_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py313h8060acc_1
  - mathjax=2.7.7=ha770c72_3
  - mdurl=0.1.2=pyhd8ed1ab_1
  - multiqc=1.28=pyhdfd78af_0
  - narwhals=1.31.0=pyhd8ed1ab_0
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - nspr=4.36=h5888daf_0
  - nss=3.108=h159eef7_0
  - openjdk=23.0.2=h68779a4_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pcre2=10.44=hba22ea6_2
  - perl=5.32.1=7_hd590300_perl5
  - pillow=11.1.0=py313h8db990d_0
  - pip=25.0.1=pyh145f28c_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - plotly=6.0.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.10.1=pyh10f6f8f_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.2=hf636f53_101_cp313
  - python-dotenv=1.0.1=pyhd8ed1ab_1
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python_abi=3.13=5_cp313
  - pyyaml=6.0.2=py313h8060acc_2
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - regex=2024.11.6=py313h536fd9c_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=13.9.4=pyhd8ed1ab_1
  - rich-click=1.8.8=pyhd8ed1ab_0
  - rpds-py=0.23.1=py313h6071e0b_0
  - salmon=1.10.3=h45fbf2d_4
  - samtools=1.21=h96c455f_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.49.1=h9eae976_2
  - staden_io_lib=1.15.0=hfc9290b_4
  - tbb=2022.1.0=h4ce085d_0
  - tiktoken=0.9.0=py313h3f234b3_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typeguard=4.4.2=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py313h536fd9c_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - corals==0.1.7
    - joblib==1.4.2
    - llvmlite==0.44.0
    - numba==0.61.0
    - numpy==1.26.4
    - pandas==2.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - scikit-learn==1.6.1
    - scipy==1.15.2
    - six==1.17.0
    - threadpoolctl==3.6.0
    - tzdata==2025.2
